apiVersion: v1
kind: Service
metadata:
  name: external-legacy-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-legacy-service
subsets:
  - addresses:
      - ip: 172.18.0.1
    ports:
      - port: 80
